### ISSUE TITLE
help, bored at school, can't access discord!!

### ISSUE THREAD

**Issue by Sid-003** [dotnetbattleroyale/meme-storage#2]
also was wondering where the discussion repo went

**Comment by k-boyle** [comment]
rip

**Comment by Kyle-Undefined** [comment]
it got sniped from 153m

**Comment by Sid-003** [comment]
it was me who sniped you

**Comment by Sid-003** [comment]
i will close this issue since I am almost out of school, will reopen tomorrow

**Comment by ghost** [comment]
reopening: am bored at school

**Comment by trinitrotoluene** [comment]
that's unfortunate.

**Comment by ghost** [comment]
closing: school finished
